"""Tests for pipeline.content_cleaner."""

from __future__ import annotations

from pipeline.content_cleaner import clean_content, clean_dict

# ---- clean_content -------------------------------------------------------


def test_clean_content_handles_empty_input():
    assert clean_content("") == ""
    assert clean_content(None) == ""


def test_clean_content_replaces_em_dash_with_hyphen():
    out = clean_content("Hello—world")  # em dash U+2014
    assert "—" not in out
    assert "Hello-world" in out


def test_clean_content_replaces_en_dash_with_hyphen():
    out = clean_content("ages 8–10")  # en dash U+2013  # noqa: RUF001
    assert "–" not in out  # noqa: RUF001
    assert "ages 8-10" in out


def test_clean_content_strips_ai_generated_disclaimer():
    out = clean_content("Worksheet body. AI-generated content. Disclaimer: AI was used.")
    lower = out.lower()
    assert "ai-generated" not in lower
    assert "disclaimer" not in lower


def test_clean_content_strips_generated_by_ai_phrase():
    out = clean_content("Lesson content. Generated by AI assistant.")
    assert "generated by" not in out.lower()


def test_clean_content_normalises_excessive_whitespace():
    out = clean_content("word1     word2\n\n\n\n\nword3")
    assert "     " not in out
    assert "\n\n\n" not in out


def test_clean_content_preserves_normal_text():
    """Legitimate content is not corrupted."""
    text = "Photosynthesis is the process by which plants make food."
    assert clean_content(text) == text


def test_clean_content_does_not_corrupt_the_word_generated_in_normal_use():
    """Spec deviation from v1: ``generated`` outside an AI-disclaimer context is kept."""
    text = "The data was generated by an experiment in our science class."
    out = clean_content(text)
    # The phrase "generated by an experiment" is legitimate; only AI-disclaimer
    # patterns should be stripped.
    assert "generated by an experiment" in out


# ---- clean_dict ----------------------------------------------------------


def test_clean_dict_recursively_cleans_string_values():
    data = {"a": "hello—world", "b": {"c": "ages 8–10"}}  # noqa: RUF001
    out = clean_dict(data)
    assert "—" not in out["a"]
    assert "–" not in out["b"]["c"]  # noqa: RUF001


def test_clean_dict_preserves_non_string_values():
    data = {"name": "x—y", "count": 42, "ratio": 1.5, "enabled": True}
    out = clean_dict(data)
    assert out["count"] == 42
    assert out["ratio"] == 1.5
    assert out["enabled"] is True


def test_clean_dict_handles_lists():
    data = {"items": ["a—b", "c–d"]}  # noqa: RUF001
    out = clean_dict(data)
    assert out["items"] == ["a-b", "c-d"]
