"""Strip AI-tell markers and normalise punctuation/whitespace.

Applied after Gemini returns text but before validation, so any em/en dashes
or stray disclaimer phrasing the model produced won't trip the validator.
"""

from __future__ import annotations

import re
from typing import Any

# Patterns that look like AI-generated content disclaimers. Matched
# case-insensitively. Order matters slightly — broader patterns first so
# narrower fragments don't leave orphan substrings behind.
_AI_DISCLAIMER_PATTERNS: list[re.Pattern[str]] = [
    re.compile(r"This (?:content|resource) was (?:.+?)generated(?:.+?)(?:[.!?]|$)", re.IGNORECASE),
    re.compile(r"Note:\s*.*?generated.*?AI.*?(?:[.!?]|$)", re.IGNORECASE),
    re.compile(r"Disclaimer:\s*.*?AI.*?(?:[.!?]|$)", re.IGNORECASE),
    re.compile(r"Generated by\s+[\w ]*?AI[\w ]*?\.?", re.IGNORECASE),
    re.compile(r"Created by\s+[\w ]*?AI[\w ]*?\.?", re.IGNORECASE),
    re.compile(r"AI-generated\s+content\.?", re.IGNORECASE),
    re.compile(r"\bAI-generated\b\.?", re.IGNORECASE),
    re.compile(r"\bAI generated\b\.?", re.IGNORECASE),
    re.compile(r"\(AI[^)]*?generated[^)]*?\)", re.IGNORECASE),
    re.compile(r"\[AI[^\]]*?generated[^\]]*?\]", re.IGNORECASE),
]


def clean_content(text: str | None) -> str:
    """Return ``text`` with dashes normalised and AI tells removed."""
    if not text:
        return ""

    # Em dash (U+2014) and en dash (U+2013) → ASCII hyphen.
    text = text.replace("—", "-").replace("–", "-")  # noqa: RUF001

    for pattern in _AI_DISCLAIMER_PATTERNS:
        text = pattern.sub("", text)

    # Collapse runs of spaces/tabs, then cap blank lines at one empty line.
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n\s*\n\s*\n+", "\n\n", text)

    return text.strip()


def clean_dict(data: Any) -> Any:
    """Recursively run :func:`clean_content` on every string value in a structure."""
    if isinstance(data, dict):
        return {key: clean_dict(value) for key, value in data.items()}
    if isinstance(data, list):
        return [clean_dict(item) for item in data]
    if isinstance(data, str):
        return clean_content(data)
    return data
